import { Stage } from './types';

export const STAGES: Stage[] = [
  {
    id: 'spark',
    name: 'THE SPARK',
    subtitle: 'Problem Discovery',
    icon: 'Lightbulb',
    description: 'What problem are you solving? Who has it?',
    mentor_mood: 'thinking',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'hunt',
    name: 'THE HUNT',
    subtitle: 'Market Research',
    icon: 'Search',
    description: 'Find real people talking about this problem',
    mentor_mood: 'teaching',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'who',
    name: 'THE WHO',
    subtitle: 'Customer Definition',
    icon: 'Users',
    description: "Get specific about who you're building for",
    mentor_mood: 'challenging',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'shape',
    name: 'THE MODEL',
    subtitle: 'Business Logic',
    icon: 'LayoutGrid',
    description: 'How does this actually work as a business?',
    mentor_mood: 'teaching',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'look',
    name: 'THE FACE',
    subtitle: 'Visual Identity',
    icon: 'Palette',
    description: 'Give your idea a name, look, and personality',
    mentor_mood: 'hyped',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'build',
    name: 'THE BUILD',
    subtitle: 'Prototype',
    icon: 'Monitor',
    description: 'Make the fastest, ugliest version that works',
    mentor_mood: 'shipping',
    color: 'var(--zagon-accent)',
  },
  {
    id: 'test',
    name: 'THE TEST',
    subtitle: 'Validation',
    icon: 'FlaskConical',
    description: 'Put it in front of real people',
    mentor_mood: 'thinking',
    color: 'var(--zagon-accent)',
  },
];
