import { Tool } from './types';

export const TOOLS: Record<string, Tool> = {
  reddit: {
    name: 'Reddit',
    url: 'https://reddit.com',
    description: 'Find real people discussing problems',
    stages: ['hunt'],
    icon: 'MessageSquare',
  },
  google_trends: {
    name: 'Google Trends',
    url: 'https://trends.google.com',
    description: 'Check if interest is growing or dying',
    stages: ['hunt'],
    icon: 'TrendingUp',
  },
  answer_the_public: {
    name: 'AnswerThePublic',
    url: 'https://answerthepublic.com',
    description: 'See what questions people ask about any topic',
    stages: ['hunt'],
    icon: 'HelpCircle',
  },
  coolors: {
    name: 'Coolors',
    url: 'https://coolors.co',
    description: 'Generate color palettes in seconds',
    stages: ['look'],
    icon: 'Palette',
  },
  namelix: {
    name: 'Namelix',
    url: 'https://namelix.com',
    description: 'AI business name generator',
    stages: ['look'],
    icon: 'Type',
  },
  canva: {
    name: 'Canva',
    url: 'https://canva.com',
    description: 'Design anything — logos, posts, presentations',
    stages: ['look', 'shape'],
    icon: 'PenTool',
  },
  gemini: {
    name: 'Google Gemini',
    url: 'https://gemini.google.com',
    description: 'Free AI image generation for logo concepts',
    stages: ['look'],
    icon: 'Image',
  },
  lovable: {
    name: 'Lovable',
    url: 'https://lovable.dev',
    description: 'AI builds a working website from a description',
    stages: ['build'],
    icon: 'Rocket',
  },
  carrd: {
    name: 'Carrd',
    url: 'https://carrd.co',
    description: 'One-page website in 15 minutes',
    stages: ['build'],
    icon: 'Globe',
  },
  figma: {
    name: 'Figma',
    url: 'https://figma.com',
    description: 'Design mockups and clickable prototypes',
    stages: ['build'],
    icon: 'PenTool',
  },
  v0: {
    name: 'v0',
    url: 'https://v0.dev',
    description: 'AI generates UI components from text',
    stages: ['build'],
    icon: 'Code',
  },
  google_forms: {
    name: 'Google Forms',
    url: 'https://forms.google.com',
    description: 'Quick surveys and feedback forms',
    stages: ['who', 'test'],
    icon: 'FileText',
  },
  tally: {
    name: 'Tally',
    url: 'https://tally.so',
    description: 'Beautiful free form builder',
    stages: ['test'],
    icon: 'CheckSquare',
  },
  loom: {
    name: 'Loom',
    url: 'https://loom.com',
    description: 'Record a video walkthrough of your prototype',
    stages: ['test'],
    icon: 'Video',
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    description: 'AI thinking partner',
    stages: ['spark', 'hunt', 'who', 'shape', 'look', 'build', 'test'],
    icon: 'Sparkles',
  },
};
